// Original, self-contained vector illustrations used in place of photography.
// Note: this environment has no AI image-generation tool, so these flat-style
// SVGs (not photos, not generated by an external model) stand in as modern,
// professional visuals. Swap the <img> "photo-*" placeholders in each page
// for real campus photography or licensed/generated imagery before launch.

export function HeroIllustration(props) {
  return (
    <svg viewBox="0 0 520 420" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
      <ellipse cx="260" cy="380" rx="220" ry="24" fill="#1e3a8a" opacity="0.06" />
      {/* building */}
      <rect x="120" y="150" width="280" height="190" rx="10" fill="#2563eb" />
      <rect x="120" y="150" width="280" height="34" rx="10" fill="#1e40af" />
      <rect x="150" y="210" width="46" height="56" rx="6" fill="#eff6ff" />
      <rect x="212" y="210" width="46" height="56" rx="6" fill="#eff6ff" />
      <rect x="274" y="210" width="46" height="56" rx="6" fill="#eff6ff" />
      <rect x="336" y="210" width="46" height="56" rx="6" fill="#eff6ff" />
      <rect x="228" y="286" width="64" height="54" rx="6" fill="#1e40af" />
      <rect x="248" y="300" width="24" height="40" rx="2" fill="#fbbf24" />
      {/* roof pediment */}
      <path d="M100 150 L260 90 L420 150 Z" fill="#1e3a8a" />
      <rect x="245" y="106" width="30" height="30" rx="4" fill="#fbbf24" />
      {/* flag */}
      <rect x="258" y="60" width="4" height="46" fill="#334155" />
      <path d="M262 60 L296 70 L262 80 Z" fill="#059669" />
      {/* ground / garden */}
      <path d="M40 340 Q260 320 480 340 L480 360 L40 360 Z" fill="#d1fae5" />
      <circle cx="90" cy="330" r="18" fill="#059669" />
      <circle cx="430" cy="332" r="22" fill="#059669" />
      {/* students */}
      <g>
        <circle cx="170" cy="356" r="10" fill="#f59e0b" />
        <rect x="160" y="366" width="20" height="26" rx="6" fill="#1d4ed8" />
      </g>
      <g>
        <circle cx="340" cy="358" r="10" fill="#fbbf24" />
        <rect x="330" y="368" width="20" height="26" rx="6" fill="#047857" />
      </g>
      <g>
        <circle cx="255" cy="362" r="10" fill="#f59e0b" />
        <rect x="245" y="372" width="20" height="26" rx="6" fill="#d97706" />
      </g>
    </svg>
  );
}

export function BookIllustration(props) {
  return (
    <svg viewBox="0 0 200 160" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
      <rect x="20" y="40" width="160" height="90" rx="8" fill="#eff6ff" />
      <path d="M100 48 L100 122" stroke="#2563eb" strokeWidth="3" />
      <path d="M28 52 C55 42 80 46 100 56 C120 46 145 42 172 52 L172 116 C145 106 120 110 100 120 C80 110 55 106 28 116 Z" fill="#2563eb" />
      <circle cx="100" cy="30" r="14" fill="#fbbf24" />
    </svg>
  );
}

export function ContactIllustration(props) {
  return (
    <svg viewBox="0 0 400 320" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
      <rect x="40" y="60" width="320" height="200" rx="16" fill="#eff6ff" />
      <rect x="70" y="90" width="130" height="14" rx="7" fill="#bfdbfe" />
      <rect x="70" y="118" width="180" height="10" rx="5" fill="#dbeafe" />
      <rect x="70" y="140" width="150" height="10" rx="5" fill="#dbeafe" />
      <rect x="70" y="180" width="110" height="34" rx="8" fill="#2563eb" />
      <circle cx="290" cy="150" r="46" fill="#fef3c7" />
      <circle cx="290" cy="150" r="20" fill="#f59e0b" />
    </svg>
  );
}

export function FacilityIcon({ children, className = "" }) {
  return (
    <div className={`w-12 h-12 rounded-xl bg-brand-50 grid place-items-center text-brand-700 ${className}`}>
      {children}
    </div>
  );
}
